spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/capstone1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create